AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/umts-custom-cops/version.rb'
