Metrics/LineLength:
  Max: 100

# I know which one I want to write.
Style/AndOr:
  Enabled: false

# And again.
Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/umts-custom-cops/version.rb'

Style/FileName:
  Enabled: false
