language: ruby
cache:
  directories:
    - gemfiles/vendor/bundle
rvm:
  - 2.5.9
  - 2.6.7
  - 2.7.3
gemfile:
  - gemfiles/Gemfile-rails52
  - gemfiles/Gemfile-rails60
  - gemfiles/Gemfile-rails61
jobs:
  exclude:
    - rvm: 2.7.3
      gemfile: gemfiles/Gemfile-rails52

env:
  global:
    - CC_TEST_REPORTER_ID=2e3996c4e1980943b0b1350ecfccc3c7f1adf90952d7a6c176b4d4bcf4e6b0c6

before_install:
  - gem update --system
  - gem install bundler
install:
  - bin/setup
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    recipients:
      - transit-it@admin.umass.edu
